# CI de Nivel 01 - Disparo manual a partir de 1 clique

# Nome do pipeline
name: 'Execução Manual'

# Gatilho de execução manual
on:
  workflow_dispatch:

# Trabalhos (jobs)
jobs:
  e2e-testes:

    # Máquina que vai executar
    runs-on: ubuntu-latest

    steps:
      # Clonar o repositório
      - uses: actions/checkout@v4

      # Instalar Node.js
      - name: Configurando Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # Instalar Yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      # Instalar dependências
      - name: Instalando dependências
        run: yarn

      # Instalar Playwright (navegadores)
      - name: Instalando Playwright
        run: yarn playwright install

      # Executar os testes e2e
      - name: Executando Testes e2e
        run: yarn run e2e
